# Generated by Django 4.2.7 on 2026-06-12 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('headphone', '耳机'), ('card_reader', '读卡器'), ('reservation_screen', '预约屏'), ('seat_indicator', '座位提示器')], max_length=30, verbose_name='设备类别')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('inspection_cycle_days', models.PositiveIntegerField(default=30, verbose_name='检修周期(天)')),
                ('status', models.CharField(choices=[('available', '可使用'), ('borrowed', '已借出'), ('pending_inspection', '待检修'), ('processing', '处理中'), ('pending_review', '待复核'), ('restored', '恢复可用'), ('suspended', '停用留置')], default='available', max_length=30, verbose_name='设备状态')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='上次检修日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.area', verbose_name='所在区域')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_devices', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('duty', '值班人员'), ('reviewer', '复核人员')], default='duty', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.CreateModel(
            name='DeviceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('fault', '故障登记'), ('borrow', '借用'), ('return', '归还'), ('cleaning', '清洁记录'), ('suspend', '临时停用'), ('inspect', '检修处理'), ('review', '复核确认'), ('restore', '恢复可用')], max_length=20, verbose_name='记录类型')),
                ('status_from', models.CharField(blank=True, choices=[('available', '可使用'), ('borrowed', '已借出'), ('pending_inspection', '待检修'), ('processing', '处理中'), ('pending_review', '待复核'), ('restored', '恢复可用'), ('suspended', '停用留置')], max_length=30, null=True, verbose_name='流转前状态')),
                ('status_to', models.CharField(blank=True, choices=[('available', '可使用'), ('borrowed', '已借出'), ('pending_inspection', '待检修'), ('processing', '处理中'), ('pending_review', '待复核'), ('restored', '恢复可用'), ('suspended', '停用留置')], max_length=30, null=True, verbose_name='流转后状态')),
                ('fault_level', models.CharField(blank=True, choices=[('low', '低'), ('medium', '中'), ('high', '高')], max_length=10, null=True, verbose_name='故障等级')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='复核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='devices.device', verbose_name='设备')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '设备记录',
                'verbose_name_plural': '设备记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
